var n=!0,t=!1;
(function(){function p(){this.b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="}function q(){this.s()}Array.prototype.indexOf||(Array.prototype.indexOf=function(b,a){var d=this.length>>>0,c=Number(a)||0,c=0>c?Math.ceil(c):Math.floor(c);for(0>c&&(c+=d);c<d;c++)if(c in this&&this[c]===b)return c;return-1});(function(){if(typeof window.SC_ContainerElement!="function"){var b=function(a,b){var c=document.getElementById(b+a)||document.getElementById(b+"_"+a);if(c)return c;for(var c=
document.getElementsByTagName("ins"),e=0;e<c.length;e++)if(c[e].getAttribute("class")=="SC_TBlock"&&c[e].getAttribute("data-ad-block")==a&&!c[e].getAttribute("data-ad-built"))return c[e]};window.SC_ContainerElement=function(a,d,c){d||(d="SC_TBlock_");var e=b(a,d);e&&c&&SC_ContainerMarkBuilt(a,d);if(!e)throw Error("No one div for ["+a+"]");return e};window.SC_ContainerMarkBuilt=function(a,d){var c=b(a,d);c&&c.setAttribute("data-ad-built","1")}}}).call();var u={get:function(b,a){typeof a==="undefined"&&
(a=null);var d=document.cookie,c=b+"=",e=d.indexOf("; "+c);if(e==-1){e=d.indexOf(c);if(e!==0)return a}else e=e+2;var f=document.cookie.indexOf(";",e);if(f==-1)f=d.length;return decodeURIComponent(d.substring(e+c.length,f))},set:function(b,a,d,c){var e=new Date,c=c||"domain",f="/";if(a){d=e.getTime()+d*6E4;c=="session"&&(d=0)}else d=e.getTime()-1;d&&(d=(new Date(d)).toGMTString());c=="page"&&(f="");b=b+"="+encodeURIComponent(a);f&&(b=b+("; path="+f));d&&(b=b+("; expires="+d));document.cookie=b}},g=
{G:43200,C:function(b){function a(){try{k.doScroll("left")}catch(b){setTimeout(a,50);return}d("poll")}function d(a){if(!(a.type=="readystatechange"&&h.readyState!="complete")){(a.type=="load"?f:h)[s](l+a.type,d,t);if(!c&&(c=n))b.call(f,a.type||a)}}var c=t,e=n,f=window,h=f.document,k=h.documentElement,m=h.addEventListener,g=m?"addEventListener":"attachEvent",s=m?"removeEventListener":"detachEvent",l=m?"":"on";if(h.readyState=="complete")b.call(f,"lazy");else{if(!m&&k.doScroll){try{e=!f.frameElement}catch(j){}e&&
a()}h[g](l+"DOMContentLoaded",d,t);h[g](l+"readystatechange",d,t);f[g](l+"load",d,t)}},log:function(b){window._sc_dbg&&console.log(b)},N:function(){return{w:document.documentElement.clientWidth||window.innerWidth||document.body.clientWidth,h:document.documentElement.clientHeight||window.innerHeight||document.body.clientHeight}},k:function(b){var a=document.getElementById(b);g.log("sizeInfo->blockSize["+b+"]: "+a.offsetWidth+"x"+a.offsetHeight);return{w:a.offsetWidth,h:a.offsetHeight}},g:function(b){var a=
g.N();return"sz_"+b+"_"+(window.outerWidth||a.w)},D:function(b){var a=u.get(g.g(b));g.log("sizeInfo->get by ["+g.g(b)+"] => "+a);if(!a)return a;try{a=JSON.parse(a)}catch(d){return null}return a},F:function(b,a){g.C(function(){function d(a){g.log("sizeInfo->set ["+g.g(b)+"] => "+JSON.stringify(a));u.set(g.g(b),JSON.stringify(a),g.G)}var c=g.k(a);if(c.w&&c.h)return d(c);var e=10,f=setInterval(function(){var b=g.k(a);b.w&&b.h&&d(b);--e===0&&clearInterval(f)},500)})},Q:function(b,a){g.F(b,a)}},x=["UNKNOWN",
"ETHERNET","WIFI","CELL_2G","CELL_3G"];q.prototype.s=function(){this.win={w:0,h:0};if(document&&document.documentElement){if(document.documentElement.clientWidth)this.win.w=document.documentElement.clientWidth;if(document.documentElement.clientHeight)this.win.h=document.documentElement.clientHeight}this.screen={width:screen.width||-1,height:screen.height||-1,colorDepth:screen.colorDepth||0,pixelDepth:screen.pixelDepth||0};var b=this.u();this.navigator={language:navigator.language||"",browserLanguage:navigator.browserLanguage||
"",systemLanguage:navigator.systemLanguage||"",userLanguage:navigator.userLanguage||"",platform:navigator.platform||"",vendor:navigator.vendor||"",timeZone:(new Date).getTimezoneOffset()*-1/60,date:new Date,hour:(new Date).getHours(),width:b.width||-1,height:b.height||-1,plugins:this.t(),flashVersion:this.r()};this.navigator.connectionType="undef";typeof navigator.P!=="undefined"&&x[navigator.connection.type]&&(this.navigator.connectionType=x[navigator.connection.type])};q.prototype.f=function(b){function a(){return""}
var d=new p;if(typeof JSON!=="undefined")if(typeof JSON.stringify!=="undefined")a=JSON.stringify;else if(typeof JSON.d!=="undefined")a=JSON.d;return d.d(a(b))};q.prototype.q=function(){return this.f(this)};q.prototype.t=function(){var b=[],a;for(i=0;i<navigator.plugins.length;i++){a=navigator.plugins[i].name.replace(/[^A-Za-z 0-9 \.,\?""!@#\$%\^&\*\(\)-_=\+;:<>\/\\\|\}\{\[\]`~]*/g,"").trim();a!==""&&b.push(a)}var d,c;for(d=b.length;d;)for(a=--d;a>0;)if(b[d]===b[--a]){for(c=a;--a&&b[d]===b[a];);d=
d-b.splice(a+1,c-a).length}return b};q.prototype.u=function(){var b={};if(typeof window.innerWidth!="undefined"){b.width=window.innerWidth;b.height=window.innerHeight}else if(typeof document.documentElement!=="undefined"&&typeof document.documentElement.clientWidth!=="undefined"&&document.documentElement.clientWidth!==0){b.width=document.documentElement.clientWidth;b.height=document.documentElement.clientHeight}else{b.width=document.getElementsByTagName("body")[0].clientWidth;b.height=document.getElementsByTagName("body")[0].clientHeight}return b};
q.prototype.r=function(){try{try{var b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");try{b.O="always"}catch(a){return"6.0.0"}}catch(d){}return(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,".").match(/^\.?(.+)\.?$/)[1]}catch(c){try{if(navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,".").match(/^\.?(.+)\.?$/)[1]}catch(e){}}return t};
p.prototype.H=function(b){for(var a="",d,c,e,f,h,k=0,b=b.replace(/[^A-Za-z0-9\+\/\=]/g,"");k<b.length;){d=this.b.indexOf(b.charAt(k++));c=this.b.indexOf(b.charAt(k++));f=this.b.indexOf(b.charAt(k++));h=this.b.indexOf(b.charAt(k++));d=d<<2|c>>4;c=(c&15)<<4|f>>2;e=(f&3)<<6|h;a=a+String.fromCharCode(d);f!=64&&(a=a+String.fromCharCode(c));h!=64&&(a=a+String.fromCharCode(e))}return a=this.z(a)};p.prototype.A=function(b){for(var b=b.replace(/\r\n/g,"\n"),a="",d=0;d<b.length;d++){var c=b.charCodeAt(d);if(c<
128)a=a+String.fromCharCode(c);else{if(c>127&&c<2048)a=a+String.fromCharCode(c>>6|192);else{a=a+String.fromCharCode(c>>12|224);a=a+String.fromCharCode(c>>6&63|128)}a=a+String.fromCharCode(c&63|128)}}return a};p.prototype.z=function(b){for(var a="",d=0,c=0,e=0;d<b.length;){c=b.charCodeAt(d);if(c<128){a=a+String.fromCharCode(c);d++}else if(c>191&&c<224){e=b.charCodeAt(d+1);a=a+String.fromCharCode((c&31)<<6|e&63);d=d+2}else{e=b.charCodeAt(d+1);c3=b.charCodeAt(d+2);a=a+String.fromCharCode((c&15)<<12|
(e&63)<<6|c3&63);d=d+3}}return a};p.prototype.d=function(b){for(var a="",d,c,e,f,h,k,m=0,b=this.A(b);m<b.length;){d=b.charCodeAt(m++);c=b.charCodeAt(m++);e=b.charCodeAt(m++);f=d>>2;d=(d&3)<<4|c>>4;h=(c&15)<<2|e>>6;k=e&63;isNaN(c)?h=k=64:isNaN(e)&&(k=64);a=a+this.b.charAt(f)+this.b.charAt(d)+this.b.charAt(h)+this.b.charAt(k)}return a};(function(){function b(a){this.m(a)}function a(a){for(var b=[],c=0;c<a.length;c++)b.push(a.charCodeAt(c)+c);return String.fromCharCode.apply(String,b)}function d(){for(var a=
[],b=document.getElementsByTagName("head")[0].getElementsByTagName("meta"),c=0;c<b.length;c++)b[c].name.toLowerCase()=="description"&&a.push(b[c].content);return a.join(",")}b.prototype={m:function(a){a||(a={});this.a=a;this.a.block_settings||(this.a.block_settings={});this.id=a.id;var b;if(!(b=a.domain)){b=[];for(var c=0;c<15;c++)b.push("ae0vqfisqlu9o|{".charCodeAt(c)-c);b=String.fromCharCode.apply(String,b)}this.domain=b;this.L();this.i=new q;this.o=a.settings;this.j=a.prefix||"SC_TBlock_";var d;
try{var e=(new p).H(this.o);d=JSON.parse(e)}catch(g){d={}}if(d.prefixName)this.j=d.prefixName},L:function(){this.K()},K:function(){var a="_sc_sync_"+this.domain;if(!window[a]){window[a]=1;var a=document.createElement("script"),b=encodeURIComponent("//"+this.domain+"/csync?Id="+this.id+"&js=1&_rnd="+Math.random());a.type="text/javascript";a.src="//sync.user-api.com/?src=ad3&rurl="+b;document.getElementsByTagName("head")[0].appendChild(a)}},p:function(a){var b="_sc_d_sync_"+this.domain+"_"+a.join("_");
if(!window[b]){window[b]=1;this.M();b=document.createElement("script");b.type="text/javascript";b.src="//"+this.domain+"/u?Id="+a.join("_");document.body.appendChild(b)}},n:function(b,c){var e,m=[];e=document.referrer;try{window.opener&&window.opener.document&&(e=window.opener.document.location.toString())}catch(q){}var s=navigator.cookieEnabled||"cookie"in document&&(document.cookie.length>0||(document.cookie="test").indexOf.call(document.cookie,"test")>-1),l={},j,r=["SC_rich","SC_catfish"],v;for(v in r)if(r.hasOwnProperty(v))(j=
this.c(v,""))&&(l[v]=j);(j=g.D(this.id))&&(j=j.w+"x"+j.h);e={Id:b.join("_"),uid:this.c("uuid1",""),sync:window.__sc_uid_synced||"0",hours:(new Date).getHours(),ajax:c?"1":"0",domain:this.domain,cld:this.a.click_domain||"",clt:this.a.click_track_url||"",unq:this.unique,sub_id:this.a.subid,cookies:s?"1":"0",_c:this.i.f(l),redir:this.a.redir,RNum:Math.floor(Math.random()*1E4),Referer_:(new p).d(a(e.substring(0,512))),docurl_:(new p).d(a(document.location.href)),client_info:this.i.q(),doc_inf:this.i.f({title:encodeURIComponent(document.title),
description:encodeURIComponent(d()),charSet:document.characterSet}),set:this.o,ver:"8",add_params:this.a.add_params,bls:j};e.doc_inf.length>1024&&delete e.doc_inf;s="";j=this.a._sc_params||{};var r=this.a._sc_debug||{},l={},o;j||(j={});r||(r={});for(o in j)j.hasOwnProperty(o)&&(l[o]=j[o]);for(o in r)r.hasOwnProperty(o)&&(l[o]=r[o]);o=0;for(var u in l)o++;o===0||(s=s+("&_sc_debug="+this.i.f(l)));for(var w in e)e.hasOwnProperty(w)&&e[w]&&m.push(encodeURIComponent(w)+"="+encodeURIComponent(e[w]));return m.join("&")+
s},I:function(a){var b=SC_ContainerElement(this.id,this.j);b.innerHTML="";var c=document.createElement("iframe");b.appendChild(c);c.style.cssText="width:100%;";var a={frameborder:"0",marginheight:"0",marginwidth:"0",scrolling:"no",id:"SC_TBlock_"+this.id+"_frame",src:a+"&iframe=1"},d;for(d in a)a.hasOwnProperty(d)&&c.setAttribute(d,a[d]);window.addEventListener("message",function(a){if(a.data.type=="frameHeightSet")c.style.height=a.data.height},t)},v:function(){this.c("uuid1",t);for(var a,b=0;b<this.e.length;b++){a=
this.e[b];var c="//"+this.domain+"/a?"+this.n([a]);if(this.a.iframe)this.I(c);else{if(a=SC_ContainerElement(a,this.j))a.innerHTML="";a=document.createElement("script");a.type="text/javascript";a.src=c;document.getElementsByTagName("body")[0].appendChild(a)}}},l:function(){var a=this;if(a.id&&a.id!="undefined"){var b=String(a.id).split(/_/);this.e=[];for(var c in b)b.hasOwnProperty(c)&&this.e.push(b[c]);if(this.e.length===0)throw Error("No one div for ["+a.id+"]");a.p(this.e);var d=50,e=setInterval(function(){if(--d===
0||a.c("uuid1",t)!==t||window.__sc_uid_synced){clearInterval(e);a.v()}},20)}},B:function(a,b){var c=a;if(typeof a==="object"){this.m(a);c=a.id}this.p([c]);var c="//"+this.domain+"/a?"+this.n([c],n),d;if(typeof XMLHttpRequest!="undefined")d=new XMLHttpRequest;else try{d=new ActiveXObject("Msxml2.XMLHTTP")}catch(e){try{d=new ActiveXObject("Microsoft.XMLHTTP")}catch(g){d=0}}if(d){d.onreadystatechange=function(){if(d.readyState==4){if(d.status==200){var a=d.responseText,a=JSON.parse(a);return b(null,
a)}return b(Error("Response status: "+d.status))}};d.open("GET",c,n);d.send(null)}else b(Error("no ajax object"))},J:function(){var a=n;typeof this.a.site_cookies!="undefined"&&(a=this.a.site_cookies);if(a)return[106323,101008].indexOf(parseInt(this.id,10))!==-1?t:n},M:function(){if(this.J()){var a="SC_unique_"+this.id,b=1;this.c(a,0)&&(b=0);this.unique=b;var c="."+document.domain.split("www.").join(""),d=new Date;d.setDate(d.getDate()+1);d.setHours(0,0,0,0);document.cookie=a+"="+b+";expires="+d.toGMTString()+
";path=/;domain="+c}},c:function(a,b){return u.get(a,b)}};var c;if(!window.sc_adv_out||!Array.isArray(window.sc_adv_out)){c=new b({id:window.SC_CId,domain:window.SC_Domain,settings:window.SC_Set||"",iframe:window.SC_IFrame||0,subid:window.SC_SubId||"",redir:window.SC_redir,add_params:window.SC_add_params,_sc_params:window._sc_params,_sc_debug:window._sc_debug});window.SC_Ajax||c.l()}else for(var e;;){e=window.sc_adv_out.pop();if(!e)break;c=new b(e);c.l()}window.SC_AdvOutBuilder=c;window.SC_AdvOutBuilder.callByAjax=
c.B}).call()}).call();
